### ISSUE TITLE
Support > 1 maintainer and add maintainer info to docs

### ISSUE THREAD

**Issue by adamzolyak** [TinkurLab/monorepo-pr-labeler-action#19]
SO THAT > 1 person can be the maintainer for this action.

AC
* What is the impact of migrating from one org to another on pulls of the action by repos that have the action enabled?  Per https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/transferring-a-repository, "All links to the previous repository location are automatically redirected to the new location.".  Therefore, it shouldn't be an issue but might be worth testing with a throw-away action repo first.
* Migrate this action to an organization (ex. https://github.com/tinkurlab) vs personal to enable multiple repo maintainers and more granular permissions.
* Add docs about maintainers (who, how to become one, etc).

**Comment by adamzolyak** [comment]
Per GH Support:

Hi Adam -

I'm going to double check with the Actions team but I remember this came up before and from my testing, users of your action shouldn't have any issues specific to the redirect, things will just continue working. However, if you happen to create a repository with the same name as the repository you transferred, that would break users of the action.

But let me double check with the Actions folks if there are other things to keep in mind and I'll let you know what I hear back.

I had a chance to chat with the Actions team and though they confirmed that because of the redirect we put in place that things will just work (e.g. no need to publish a new version), they recommended creating a new repository for the action in the new location and for the old one, you can point people to the new action repository.

This will ensure that current users of the action can still use it and things won't accidentally break in the future if the redirect is broken (e.g. if you happen to create a repository with the same name, or if you rename your account and someone else takes it, etc.). Here are some examples where the Actions team did the same thing, we can see in these archived action repositories:

https://github.com/actions?q=&type=archived&language=

So in https://github.com/actions/setup-haskell, we can see the README points to a maintained fork, but the README has been updated to mention that actions/setup-haskell is unmaintained and the repository has been archived.

Hope these notes are helpful but if you have questions, please let me know -- thanks,
Robert

**Comment by anshulsahni** [comment]
@adamzolyak Any further update here?

**Comment by adamzolyak** [comment]
@anshulsahni I migrated the repo to https://github.com/TinkurLab/monorepo-pr-labeler-action.  Everything appears to be working as expected for me. I ran a test to make sure existing Action configurations that point to the old repo will still work as expected. See https://github.com/adamzolyak/actions-playground/pull/100/checks?check_run_id=3015200246.
