### ISSUE TITLE
Use Node action instead of Dockerfile

### ISSUE THREAD

**Issue by AnandChowdhary** [TinkurLab/monorepo-pr-labeler-action#31]
It currently takes over 1 minute to build this action before running it every time. I noticed that it just runs a JS file, so you can remove the Dockerfile and use a JavaScript action directly: https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action.

This way, the JS file will directly run without a build step required before it.

**Comment by adamzolyak** [comment]
@AnandChowdhary does https://github.com/TinkurLab/monorepo-pr-labeler-action/pull/30 address this need?

**Comment by AnandChowdhary** [comment]
Absolutely, this is great, thanks!
