### ISSUE TITLE
Feature request: Add folder to ignore

### ISSUE THREAD

**Issue by gvart-sellics** [TinkurLab/monorepo-pr-labeler-action#35]

**Comment by gvart-sellics** [comment]
Apart from having hidden folders ignored by default would be great to have a way to define folders that should be ignored

**Comment by adamzolyak** [comment]
@gvart-sellics thanks for your suggestion.

Currently, you can opt-in directories `you can configure one (ex. directory1) or more directories (ex. directory1|directory2|...)`.

How would you want this to work differently? Do you have an example directory structure you can share?

**Comment by adamzolyak** [comment]
Closing due to lack of followup.
