### ISSUE TITLE
Support removing the space from prefixes

### ISSUE THREAD

**Issue by joeyfigaro** [TinkurLab/monorepo-pr-labeler-action#40]
We'd like to label PRs using our official package names (including their scope), which would look like this: `@thescope/package` – but it seems that when the label is created, a space is forced onto the end of the provided prefix. This results in `@thescope/ package`.

Thank you!

**Comment by adamzolyak** [comment]
@joeyfigaro thanks for your suggestion. In reviewing the current implementation at https://github.com/TinkurLab/monorepo-pr-labeler-action/blob/master/helpers.js#L83, it seems to me that it would be a better convention to not include spaces by default while allowing spaces to be added through configuration. This would support your use case and use cases includes spaces and other formatting.
