### ISSUE TITLE
Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by sigurdga** [TinkurLab/monorepo-pr-labeler-action#60]
We get a warning from github action:

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: tinkurlab/monorepo-pr-labeler-action@4.1.4. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

I hope it is easy to update this.

**Comment by adamzolyak** [comment]
I'll bump the version this weekend. Or feel free to submit a PR.
